---
steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/sh
    args:
      - -c
      - |
        mkdir -p ~/.ssh
        gcloud secrets versions access latest --secret=cicd_ssh_private_key > ~/.ssh/id_rsa
        chmod 600 ~/root/.ssh/id_rsa
        gcloud secrets versions access latest --secret=cicd_ssh_pub_key > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
        set -x
        gcloud compute ssh --ssh-key-file=~/.ssh/id_rsa --tunnel-through-iap --zone=$_ZONE $_VM_NAME --project=$_PROJECT_ID --command='/bin/sh /root/cicddeploy.sh $_BRANCH' 

options:
  logging: CLOUD_LOGGING_ONLY
