---
steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/sh
    args:
      - -c
      - |
        mkdir -p ~/.ssh
        echo "$(gcloud secrets versions access latest --secret=cicd_ssh_private_key)" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$(gcloud secrets versions access latest --secret=cicd_ssh_pub_key)" > ~/.ssh/id_rsa.pub
        chmod 644 ~/.ssh/id_rsa.pub
        set -x
        gcloud compute ssh cicd \
            --project=learning-449114 \
            --zone=us-central1-c \
            --ssh-key-file=~/.ssh/id_rsa \
            --tunnel-through-iap \
            --command='/bin/sh /root/cicddeploy.sh'
options:
  logging: CLOUD_LOGGING_ONLY
